apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: guess-game
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: amandagusmao/guess_game-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production
        - name: FLASK_DB_HOST
          value: db
        - name: FLASK_DB_PORT
          value: "30543"
        - name: FLASK_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: FLASK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: FLASK_APP
          value: run.py
